nelmio_api_doc:
    documentation:
        info:
            title: Task Code Review
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api/v1(?!/doc$)